version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Get coverage libs
          command: go get github.com/mattn/goveralls
      - run:
          name: Run tests
          command: go test -v -cover -race -coverprofile=coverage.out
      - run:
          name: Testing path
          command: echo $GOBIN
      - run:
          name: Testing path2
          command: echo $GOPATH
      - run:
          name: Testing path3
          command: echo $GOROOT
      - run:
          name: Push coverage results
          command: $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
